### PR TITLE
(TK-297) Fix wrap-routes

### PR DESCRIPTION
**Pull request by mruzicka**
Make sure the ```wrap-routes``` function only ever modifies the handlers in bidi route trees and never the patterns. Previously it could modify even the patterns (although only less common ones) and thus corrupt the route tree.

### CODE REVIEW

**Comment by mruzicka** [comment]
@cprice404 @scottyw @rlinehan Could you please review this?

**Comment by scottyw** [comment]
@mruzicka Could you add a test to illustrate what's broken today?

**Comment by mruzicka** [comment]
@scottyw I included an example in: https://tickets.puppetlabs.com/browse/TK-297

**Comment by scottyw** [comment]
The changes make sense to me. If we could add the tests I'm +1 to merge.

**Comment by mruzicka** [comment]
Ah, ok, I misread your comment, will add some tests.

**Comment by cprice404** [comment]
I'm w/ @scottyw ; change seems reasonable, adding basic test coverage seems worthwhile.

**Comment by mruzicka** [comment]
@scottyw @cprice404 I've added the tests.

**Comment by cprice404** [comment]
+1 I'm good when you are, @scottyw

**Pull request merged**
