### PR TITLE
(MAINT) update version to 0.2.2-SNAPSHOT for dev

### PR DESCRIPTION
**Pull request by cprice404**

### CODE REVIEW

**Comment by rlinehan** [comment]
Seems like we've mostly been using Jenkins for doing releases. Any reason why you didn't do that for this?

Also, if we're doing a release seems like it would be good to add some stuff to the docs about the new `wrap-resources` function? Or at least update the changelog (which hasn't been done in a very long time)?

**Comment by cprice404** [comment]
The short version is "because I'm a terrible person".

The long version is that I couldn't get onto the VPN this weekend and this was blocking some other work that I consider to be fairly urgent, but am never going to get time to work on in the office... so it was either "break some rules" or not be able to do the other work.  So... I apologize :(

I put a note on my TODO list to add tests for the resources thing and to update the changelog.  I'll find some time for both of those ASAP.  In the meantime it might be best to go ahead and merge this because otherwise we have a non-SNAPSHOT version at HEAD, which is bad.  (And totally my fault.)

**Comment by rlinehan** [comment]
Hahaha, no worries, I just was confused about it.

> In the meantime it might be best to go ahead and merge this because otherwise we have a non-SNAPSHOT version at HEAD, which is bad. (And totally my fault.)

At HEAD of master? No we don't? The version 0.2.1 commit is only in this PR? Or am I just even more confused than I think I am?

**Comment by cprice404** [comment]
Sorry, no... wow.  I'm the one who is confused.  I thought I actually did a release to clojars yesterday, but apparently what I did was just build an 0.2.1 on my local machine.  So... I'm going to close this and we can pretend it never happened... but we should do a for-realz release soon.

**Comment by cprice404** [comment]
ZOMG

**Comment by cprice404** [comment]
I did do a clojars release yesterday.  So I do think we should merge this so that the code matches up to what we have on clojars.  Sorry, I made a big mess out of this whole thing.

**Pull request merged**
