### PR TITLE
(maint) Bidi update

### PR DESCRIPTION
**Pull request by aperiodic**

### CODE REVIEW

**Comment by rlinehan** [comment]
Would it be worthwhile to update the other dependencies while we're at it?

**Comment by aperiodic** [comment]
This one in particular is a pain point since it causes conflicts when combined with PuppetDB (currently this happens in PE-AIO primarily), but I can take a look at bumping the other ones if you'd like.

**Comment by rlinehan** [comment]
Mostly just thinking that since this is a bump to a new major version of a dependency, we should probably do at least a Y version bump of comidi, and if we're going to do that it might be worthwhile to get the others up to date.

**Comment by aperiodic** [comment]
@rlinehan I updated all of the dependencies to the newest versions that didn't cause transitive dependency conflicts with each other. The only thing not at the newest version is comidi, which is two Z releases behind; if you're okay adding an override for ring-core, we could update `comidi` to the newest Z.

**Comment by camlow325** [comment]
@aperiodic - thanks for doing this.

Would you be open to converting comidi to using clj-parent as part of this PR?  We've been incrementally adding clj-parent to various utility libraries as we've had the need to update multiple dependencies.  Seems like the ones you've updated to would work with the latest in clj-parent right now, with the exception of clj-parent using schema [1.1.1](https://github.com/puppetlabs/clj-parent/blob/0.4.3/project.clj#L81) instead of 1.1.3.  Not sure going up to 1.1.3 was critical here?

That said, I think I'm otherwise good with this as is and we could migrate to clj-parent in a later PR.

@rlinehan - WDYT?

**Comment by rlinehan** [comment]
I think given this has been open a while I'm good merging as-is. Would be good to update to clj-parent at some point though.

**Comment by rlinehan** [comment]
Also thanks @aperiodic for updating the other libraries! appreciate it.

**Pull request merged**
